on: push
name: Main workflow
jobs:
  github-action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: github-action
      uses: nocturlab/upload-to-discord@send-in-archive
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        ARCHIVE_NAME: release
      with:
        args: README.md
    - name: local action
      uses: ./
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        ARCHIVE_NAME: release
      with:
        args: README.md
    - name: github-action
      uses: nocturlab/upload-to-discord@send-in-archive
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        ARCHIVE_NAME: release
      with:
        args: ./*
